# Test Configuration for Integration Tests
# This configuration is used ONLY for testing and does not affect production

name: real_estate_data_pipeline_test
version: 1.0.0

# Spark Configuration for Tests
spark:
  app_name: RealEstateDataPipelineTest
  master: local[2]  # Use 2 cores for tests
  driver_memory: 2g  # Less memory for tests
  executor_memory: 1g

# Data Sources (same as production)
data_sources:
  properties_files:
    - real_estate_data/properties_sf.json
    - real_estate_data/properties_pc.json
  neighborhoods_files:
    - real_estate_data/neighborhoods_sf.json
    - real_estate_data/neighborhoods_pc.json
  wikipedia_db_path: data/wikipedia/wikipedia.db
  locations_file: real_estate_data/locations.json

# Embedding Configuration for Tests
embedding:
  provider: mock  # Always use mock for tests
  model_name: mock-model
  batch_size: 10
  dimension: 1024

# Output Configuration for Tests
output:
  enabled_destinations:
    - parquet  # Only use parquet for tests, no Neo4j/Elasticsearch
  
  parquet:
    base_path: data/test_output  # Different path for test output
    compression: snappy