# Configuration for multi-entity ingestion pipeline
# Reuses wiki_embed configuration structure

embedding:
  provider: ollama  # Options: ollama, gemini, voyage
  # Ollama settings
  ollama_base_url: "http://localhost:11434"
  ollama_model: "nomic-embed-text"
  # Gemini settings (if using)
  gemini_api_key: null
  gemini_model: "models/embedding-001"
  # Voyage settings (if using)
  voyage_api_key: null
  voyage_model: "voyage-3"

vector_store:
  provider: elasticsearch  # Options: chromadb, elasticsearch
  chromadb:
    path: "./data/wiki_chroma_db"
    collection_prefix: "wiki_embeddings"
  elasticsearch:
    host: "localhost"
    port: 9200
    index_prefix: "wiki"
    username: "elastic"
    password: "2GJXncaV"

data:
  source_dir: "./data/wikipedia/pages"
  registry_path: "./data/wikipedia/REGISTRY.json"
  attribution_path: "./data/wikipedia/attribution/WIKIPEDIA_ATTRIBUTION.json"
  wikipedia_db: "./data/wikipedia/wikipedia.db"  # SQLite database with summaries
  wikipedia_base: "./data/wikipedia"  # Base directory for Wikipedia data

chunking:
  method: simple  # semantic or simple
  # Semantic parser settings
  breakpoint_percentile: 90
  buffer_size: 2
  # Simple parser settings
  chunk_size: 1000
  chunk_overlap: 200
  # Embedding method selection
  embedding_method: traditional  # Options: traditional, augmented, both
  # Augmented embedding settings
  max_summary_words: 100
  max_total_words: 500
  split_oversized_chunks: false

testing:
  queries_path: "./data/wiki_test_queries.json"
  top_k: 5
  min_similarity: 0.3