# Test configuration for Neo4j-only pipeline (no Elasticsearch/search pipeline)
spark:
  app_name: "Neo4jOnlyTest"
  master: "local[2]"
  driver_memory: "2g"

data_source:
  properties_files:
    - "real_estate_data/properties_sf.json"
  neighborhoods_files: 
    - "real_estate_data/neighborhoods_sf.json"
  wikipedia_db_path: "data/wikipedia/wikipedia.db"

processing:
  enable_wikipedia_enrichment: true
  enable_field_mapping: false  # Not needed for Neo4j
  enable_embeddings: false  # Testing without embeddings

output:
  enabled_destinations:
    - "neo4j"
    - "parquet"
  parquet:
    base_path: "test_neo4j_output"
    format: "parquet"
    mode: "overwrite"
    partitioned: false
  neo4j:
    uri: "bolt://localhost:7687"
    username: "neo4j"
    # Password from NEO4J_PASSWORD env variable
    database: "neo4j"
    batch_size: 1000
    clear_before_write: true

# Explicitly disable search pipeline
search_pipeline:
  enabled: false

# Pipeline settings  
sample_size: 5  # Very small sample for quick testing
test_mode: true