# Evaluation Configuration for mxbai-embed-large
embedding:
  provider: ollama
  ollama_model: mxbai-embed-large
  ollama_host: http://localhost:11434

chromadb:
  persist_directory: ./data/wiki_chroma_db
  collection_name: gold_ollama_mxbai_embed_large

chunking:
  method: simple
  chunk_size: 1000
  chunk_overlap: 100
  
processing:
  batch_size: 32
  max_workers: 4
  verbose: true

evaluation_data:
  articles_path: common_embeddings/evaluate_data/gold_articles.json
  queries_path: common_embeddings/evaluate_data/gold_queries.json
  dataset_type: gold
