# Evaluation config for nomic-embed-text model
embedding:
  provider: ollama
  ollama_model: nomic-embed-text
  ollama_host: http://localhost:11434

chromadb:
  persist_directory: ./data/wiki_chroma_db
  collection_name: gold_ollama_nomic_embed_text

chunking:
  method: simple
  chunk_size: 1000
  chunk_overlap: 100
  
processing:
  batch_size: 32
  max_workers: 4
  verbose: true

evaluation_data:
  articles_path: common_embeddings/evaluate_data/gold_articles.json
  queries_path: common_embeddings/evaluate_data/gold_queries.json
  dataset_type: gold