# SQUACK Pipeline Configuration
# Core configuration for DuckDB-based real estate data processing pipeline
# Use environment variables for: VOYAGE_API_KEY, ELASTICSEARCH_PASSWORD

name: squack_pipeline
version: 1.0.0

# Data Sources Configuration
data_sources:
  properties_files:
    - real_estate_data/properties_sf.json
    - real_estate_data/properties_pc.json
  neighborhoods_files:
    - real_estate_data/neighborhoods_sf.json
    - real_estate_data/neighborhoods_pc.json
  wikipedia_db_path: data/wikipedia/wikipedia.db
  locations_file: real_estate_data/locations.json

# Data Processing Configuration  
data:
  input_path: real_estate_data
  output_path: ./squack_pipeline_output
  sample_size: null  # null means process all records

# DuckDB Configuration
duckdb:
  memory_limit: 8GB
  threads: 4

# Embedding Configuration (following common_embeddings patterns)
embedding:
  provider: voyage  # Options: voyage, openai, ollama, gemini, mock
  
  # Voyage AI settings (API key loaded from parent .env)
  voyage_model: voyage-3  # 1024 dimensions, best semantic understanding
  
  # OpenAI settings (if provider=openai)
  # openai_api_key: null  # Set via OPENAI_API_KEY env var
  openai_model: text-embedding-3-small
  
  # Ollama settings (if provider=ollama for local processing)
  ollama_base_url: http://localhost:11434
  ollama_model: nomic-embed-text
  
  # Mock settings (for testing without API keys)
  mock_dimension: 1024

# Text Processing Configuration
processing:
  batch_size: 50  # Smaller batches for API rate limits
  max_workers: 2  # Conservative for API limits
  show_progress: true
  rate_limit_delay: 0.1  # 100ms delay between API calls
  
  # Enable embeddings (can be disabled for faster processing)
  generate_embeddings: true
  
  # Chunking configuration
  enable_chunking: true
  chunk_method: semantic  # Options: simple, semantic, sentence, none
  chunk_size: 800
  chunk_overlap: 100
  
  # Semantic chunking parameters (for better real estate content splitting)
  breakpoint_percentile: 90
  buffer_size: 2

# Output Configuration
output:
  # List of enabled output destinations
  enabled_destinations:
    - parquet
    - elasticsearch  # Enabled for Elasticsearch output
  
  # Elasticsearch configuration (used when elasticsearch is enabled)
  elasticsearch:
    host: localhost
    port: 9200
    bulk_size: 500
    # No authentication for local development
    timeout: 30

# Logging Configuration
logging:
  level: DEBUG

# Environment Configuration
environment: development  # development, production, test

# Metadata versioning
metadata_version: "1.0"