# Configuration for Real Estate Search System
# Works with pre-indexed data from data_pipeline

environment: development
debug: false
demo_mode: true

elasticsearch:
  host: localhost
  port: 9200
  # Authentication - loaded from environment variables
  # username: elastic
  # password: your-password
  # api_key: your-api-key-here
  # cloud_id: your-cloud-id-here
  property_index: real_estate_properties
  neighborhood_index: real_estate_neighborhoods  
  wiki_chunks_index_prefix: real_estate_wikipedia
  wiki_summaries_index_prefix: real_estate_wikipedia
  request_timeout: 30
  verify_certs: false

index:
  name: properties
  alias: properties_alias
  shards: 1
  replicas: 1
  refresh_interval: 1s

search:
  default_size: 20
  max_size: 100
  default_sort: relevance
  highlight_enabled: true
  aggregations_enabled: true
  enable_fuzzy: true

indexing:
  batch_size: 100
  parallel_threads: 4
  refresh_after_index: true
  validate_before_index: true

logging:
  level: INFO
  structured: false

data:
  wikipedia_db: ../data/wikipedia/wikipedia.db

# Embedding configuration for semantic search
# Uses same Voyage-3 model as data_pipeline for consistency
embedding:
  provider: voyage
  model_name: voyage-3
  dimension: 1024
  # API key loaded from VOYAGE_API_KEY environment variable
  timeout_seconds: 30.0
  max_retries: 3