# Configuration for Real Estate Search System
# Works with pre-indexed data from data_pipeline

elasticsearch:
  host: localhost
  port: 9200
  # Authentication - uncomment and fill in if needed
  # username: elastic
  # password: your-password
  # api_key: your-api-key-here
  # cloud_id: your-cloud-id-here
  property_index: properties
  wiki_chunks_index_prefix: wiki_chunks
  wiki_summaries_index_prefix: wiki_summaries
  request_timeout: 30

# Wikipedia data location for enrichment lookups
data:
  wikipedia_db: ../data/wikipedia/wikipedia.db

# Search settings
demo_mode: true

# Logging
log_level: INFO