# Embedding Pipeline Configuration
embedding:
  provider: ollama  # Options: ollama, gemini, voyage
  # Ollama settings
  ollama_base_url: "http://localhost:11434"
  ollama_model: nomic-embed-text
  # ollama_model: mxbai-embed-large

  # Gemini settings (set GOOGLE_API_KEY env variable)
  gemini_model: "models/embedding-001"
  # Voyage settings (set VOYAGE_API_KEY env variable)
  voyage_model: "voyage-3"  # Options: voyage-3, voyage-3-lite, voyage-finance-2, voyage-multilingual-2, voyage-law-2, voyage-code-2

chromadb:
  path: "./data/real_estate_chroma_db"
  collection_prefix: "embeddings"

data:
  source_dir: "./real_estate_data"  # Real estate data directory

chunking:
  method: simple  # Options: simple (fast), semantic (slow but better boundaries)
  # Simple parser settings
  chunk_size: 512
  chunk_overlap: 50
  # Semantic parser settings (only used when method="semantic")
  breakpoint_percentile: 95
  buffer_size: 1