# Model Comparison Configuration
# Simple, clean configuration for comparing embedding models

version: "1.0"

# Evaluation settings (simple, no caching or parallel execution)
evaluation:
  dataset: gold  # Use gold standard dataset
  top_k: 10      # Retrieve top 10 results for each query

# Models to compare (sequential evaluation)
models:
  - name: nomic-embed-text
    provider: ollama
    collection_name: wikipedia_ollama_nomic_embed_text_v1
    
  - name: mxbai-embed-large  
    provider: ollama
    collection_name: wikipedia_ollama_mxbai_embed_large_v1

# Comparison settings (simple winner determination)
comparison:
  primary_metric: f1_score  # Main metric for determining winner

# Reporting configuration (simple HTML report)
reporting:
  format: html
  output_directory: ./common_embeddings/evaluate_results/comparisons